services:
  postgres:
    image: postgres:latest
    container_name: spring-rag-vector-store
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_ai_rag_vector_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
