spring:
  ai:
    vectorstore:
      pgvector:
        remove-existing-vector-store-table: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai_rag
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

logging:
  level:
    "[org.springframework.ai.chat.client.advisor]": DEBUG
