spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
  application:
    name: spring-ai-rag
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    default: local

chat:
  system-message:
    placeholders:
      companyName: DJF Development
