[versions]
junit-platform-launcher = "1.10.0"
postgresql = "42.6.0"
spring-ai = "1.0.0-M4"
spring-boot = "3.4.0"
spring-dependency-management = "1.1.6"

[libraries]
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
spring-ai-bom = { group = "org.springframework.ai", name = "spring-ai-bom", version.ref = "spring-ai" }
spring-ai-openai-spring-boot-starter = { group = "org.springframework.ai", name = "spring-ai-openai-spring-boot-starter" }
spring-ai-pgvector-store-spring-boot-starter = { group = "org.springframework.ai", name = "spring-ai-pgvector-store-spring-boot-starter" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
