spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.5
      embedding:
        options:
          model: text-embedding-ada-002
    vectorstore:
      pgvector:
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        index-type: HNSW
        initialize-schema: true
  application:
    name: spring-ai-rag
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
        jdbc:
          lob:
            "[non_contextual_creation]": true
  profiles:
    default: local

management:
  endpoint:
    prometheus:
      access: READ_ONLY
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

app:
  conversation:
    max-last-n: 1000
  chat:
    embedding:
      document: "classpath:/embedding/faq-data.json"
    system-prompt:
      placeholders:
        companyName: DJF Development
      resource: "classpath:/chat/system-message.txt"
